paru -S --noconfirm haskell-adjunctions
paru -S --noconfirm haskell-aeson
paru -S --noconfirm haskell-aeson-pretty
paru -S --noconfirm haskell-alsa-core
paru -S --noconfirm haskell-alsa-mixer
paru -S --noconfirm haskell-annotated-wl-pprint
paru -S --noconfirm haskell-ansi-terminal
paru -S --noconfirm haskell-ansi-wl-pprint
paru -S --noconfirm haskell-appar
paru -S --noconfirm haskell-asn1-encoding
paru -S --noconfirm haskell-asn1-parse
paru -S --noconfirm haskell-asn1-types
paru -S --noconfirm haskell-assoc
paru -S --noconfirm haskell-async
paru -S --noconfirm haskell-attoparsec
paru -S --noconfirm haskell-attoparsec-iso8601
paru -S --noconfirm haskell-auto-update
paru -S --noconfirm haskell-base-compat
paru -S --noconfirm haskell-base-compat-batteries
paru -S --noconfirm haskell-base-orphans
paru -S --noconfirm haskell-base16-bytestring
paru -S --noconfirm haskell-base64-bytestring
paru -S --noconfirm haskell-basement
paru -S --noconfirm haskell-bifunctors
paru -S --noconfirm haskell-binary-conduit
paru -S --noconfirm haskell-blaze-builder
paru -S --noconfirm haskell-blaze-html
paru -S --noconfirm haskell-blaze-markup
paru -S --noconfirm haskell-byteable
paru -S --noconfirm haskell-byteorder
paru -S --noconfirm haskell-call-stack
paru -S --noconfirm haskell-casa-client
paru -S --noconfirm haskell-casa-types
paru -S --noconfirm haskell-case-insensitive
paru -S --noconfirm haskell-cereal
paru -S --noconfirm haskell-charset
paru -S --noconfirm haskell-citeproc
paru -S --noconfirm haskell-clock
paru -S --noconfirm haskell-cmdargs
paru -S --noconfirm haskell-colour
paru -S --noconfirm haskell-commonmark
paru -S --noconfirm haskell-commonmark-extensions
paru -S --noconfirm haskell-commonmark-pandoc
paru -S --noconfirm haskell-comonad
paru -S --noconfirm haskell-conduit
paru -S --noconfirm haskell-conduit-extra
paru -S --noconfirm haskell-conduit-parse
paru -S --noconfirm haskell-connection
paru -S --noconfirm haskell-constraints
paru -S --noconfirm haskell-contravariant
paru -S --noconfirm haskell-cookie
paru -S --noconfirm haskell-cryptohash-sha256
paru -S --noconfirm haskell-cryptonite
paru -S --noconfirm haskell-cryptonite-conduit
paru -S --noconfirm haskell-data-default
paru -S --noconfirm haskell-data-default-class
paru -S --noconfirm haskell-data-default-instances-containers
paru -S --noconfirm haskell-data-default-instances-dlist
paru -S --noconfirm haskell-data-default-instances-old-locale
paru -S --noconfirm haskell-data-fix
paru -S --noconfirm haskell-dbus
paru -S --noconfirm haskell-dbus-hslogger
paru -S --noconfirm haskell-diff
paru -S --noconfirm haskell-digest
paru -S --noconfirm haskell-distributive
paru -S --noconfirm haskell-dlist
paru -S --noconfirm haskell-doclayout
paru -S --noconfirm haskell-doctemplates
paru -S --noconfirm haskell-easy-file
paru -S --noconfirm haskell-echo
paru -S --noconfirm haskell-ed25519
paru -S --noconfirm haskell-emojis
paru -S --noconfirm haskell-enclosed-exceptions
paru -S --noconfirm haskell-erf
paru -S --noconfirm haskell-errors
paru -S --noconfirm haskell-extensible-exceptions
paru -S --noconfirm haskell-extra
paru -S --noconfirm haskell-fast-logger
paru -S --noconfirm haskell-file-embed
paru -S --noconfirm haskell-filelock
paru -S --noconfirm haskell-free
paru -S --noconfirm haskell-fsnotify
paru -S --noconfirm haskell-generic-deriving
paru -S --noconfirm haskell-ghc-bignum-orphans
paru -S --noconfirm haskell-githash
paru -S --noconfirm haskell-glob
paru -S --noconfirm haskell-hackage-security
paru -S --noconfirm haskell-haddock-library
paru -S --noconfirm haskell-hashable
paru -S --noconfirm haskell-hi-file-parser
paru -S --noconfirm haskell-hinotify
paru -S --noconfirm haskell-hourglass
paru -S --noconfirm haskell-hpack
paru -S --noconfirm haskell-hslogger
paru -S --noconfirm haskell-hslua
paru -S --noconfirm haskell-hslua-aeson
paru -S --noconfirm haskell-hslua-classes
paru -S --noconfirm haskell-hslua-core
paru -S --noconfirm haskell-hslua-marshalling
paru -S --noconfirm haskell-hslua-module-doclayout
paru -S --noconfirm haskell-hslua-module-path
paru -S --noconfirm haskell-hslua-module-system
paru -S --noconfirm haskell-hslua-module-text
paru -S --noconfirm haskell-hslua-module-version
paru -S --noconfirm haskell-hslua-objectorientation
paru -S --noconfirm haskell-hslua-packaging
paru -S --noconfirm haskell-hsyaml
paru -S --noconfirm haskell-http
paru -S --noconfirm haskell-http-api-data
paru -S --noconfirm haskell-http-client
paru -S --noconfirm haskell-http-client-tls
paru -S --noconfirm haskell-http-conduit
paru -S --noconfirm haskell-http-download
paru -S --noconfirm haskell-http-types
paru -S --noconfirm haskell-hxt
paru -S --noconfirm haskell-hxt-charproperties
paru -S --noconfirm haskell-hxt-regex-xmlschema
paru -S --noconfirm haskell-hxt-unicode
paru -S --noconfirm haskell-indexed-traversable
paru -S --noconfirm haskell-indexed-traversable-instances
paru -S --noconfirm haskell-infer-license
paru -S --noconfirm haskell-integer-logarithms
paru -S --noconfirm haskell-invariant
paru -S --noconfirm haskell-iproute
paru -S --noconfirm haskell-ipynb
paru -S --noconfirm haskell-jira-wiki-markup
paru -S --noconfirm haskell-juicypixels
paru -S --noconfirm haskell-kan-extensions
paru -S --noconfirm haskell-lens
paru -S --noconfirm haskell-lexer
paru -S --noconfirm haskell-libmpd
paru -S --noconfirm haskell-libyaml
paru -S --noconfirm haskell-lift-type
paru -S --noconfirm haskell-lifted-async
paru -S --noconfirm haskell-lifted-base
paru -S --noconfirm haskell-lpeg
paru -S --noconfirm haskell-lua
paru -S --noconfirm haskell-lukko
paru -S --noconfirm haskell-megaparsec
paru -S --noconfirm haskell-memory
paru -S --noconfirm haskell-microlens
paru -S --noconfirm haskell-microlens-mtl
paru -S --noconfirm haskell-microlens-th
paru -S --noconfirm haskell-mime-types
paru -S --noconfirm haskell-mintty
paru -S --noconfirm haskell-monad-control
paru -S --noconfirm haskell-monad-logger
paru -S --noconfirm haskell-monad-loops
paru -S --noconfirm haskell-mono-traversable
paru -S --noconfirm haskell-mustache
paru -S --noconfirm haskell-neat-interpolation
paru -S --noconfirm haskell-netlink
paru -S --noconfirm haskell-network
paru -S --noconfirm haskell-network-bsd
paru -S --noconfirm haskell-network-uri
paru -S --noconfirm haskell-old-locale
paru -S --noconfirm haskell-old-time
paru -S --noconfirm haskell-onetuple
paru -S --noconfirm haskell-only
paru -S --noconfirm haskell-open-browser
paru -S --noconfirm haskell-optparse-applicative
paru -S --noconfirm haskell-optparse-generic
paru -S --noconfirm haskell-optparse-simple
paru -S --noconfirm haskell-pandoc-lua-marshal
paru -S --noconfirm haskell-pandoc-types
paru -S --noconfirm haskell-pantry
paru -S --noconfirm haskell-parallel
paru -S --noconfirm haskell-parsec-numbers
paru -S --noconfirm haskell-parser-combinators
paru -S --noconfirm haskell-parsers
paru -S --noconfirm haskell-path
paru -S --noconfirm haskell-path-io
paru -S --noconfirm haskell-path-pieces
paru -S --noconfirm haskell-pem
paru -S --noconfirm haskell-persistent
paru -S --noconfirm haskell-persistent-sqlite
paru -S --noconfirm haskell-pretty-hex
paru -S --noconfirm haskell-pretty-show
paru -S --noconfirm haskell-primitive
paru -S --noconfirm haskell-profunctors
paru -S --noconfirm haskell-project-template
paru -S --noconfirm haskell-quickcheck
paru -S --noconfirm haskell-random
paru -S --noconfirm haskell-reflection
paru -S --noconfirm haskell-regex-base
paru -S --noconfirm haskell-regex-compat
paru -S --noconfirm haskell-regex-posix
paru -S --noconfirm haskell-regex-tdfa
paru -S --noconfirm haskell-resource-pool
paru -S --noconfirm haskell-resourcet
paru -S --noconfirm haskell-retry
paru -S --noconfirm haskell-rio
paru -S --noconfirm haskell-rio-orphans
paru -S --noconfirm haskell-rio-prettyprint
paru -S --noconfirm haskell-safe
paru -S --noconfirm haskell-safe-exceptions
paru -S --noconfirm haskell-scientific
paru -S --noconfirm haskell-semigroupoids
paru -S --noconfirm haskell-setlocale
paru -S --noconfirm haskell-sha
paru -S --noconfirm haskell-shelly
paru -S --noconfirm haskell-silently
paru -S --noconfirm haskell-skylighting
paru -S --noconfirm haskell-skylighting-core
paru -S --noconfirm haskell-socks
paru -S --noconfirm haskell-split
paru -S --noconfirm haskell-splitmix
paru -S --noconfirm haskell-statevar
paru -S --noconfirm haskell-stm-chans
paru -S --noconfirm haskell-streaming-commons
paru -S --noconfirm haskell-strict
paru -S --noconfirm haskell-syb
paru -S --noconfirm haskell-system-filepath
paru -S --noconfirm haskell-tagged
paru -S --noconfirm haskell-tagsoup
paru -S --noconfirm haskell-tar
paru -S --noconfirm haskell-tar-conduit
paru -S --noconfirm haskell-temporary
paru -S --noconfirm haskell-texmath
paru -S --noconfirm haskell-text-conversions
paru -S --noconfirm haskell-text-icu
paru -S --noconfirm haskell-text-metrics
paru -S --noconfirm haskell-th-abstraction
paru -S --noconfirm haskell-th-compat
paru -S --noconfirm haskell-th-expand-syns
paru -S --noconfirm haskell-th-lift
paru -S --noconfirm haskell-th-lift-instances
paru -S --noconfirm haskell-th-reify-many
paru -S --noconfirm haskell-these
paru -S --noconfirm haskell-time-compat
paru -S --noconfirm haskell-timezone-olson
paru -S --noconfirm haskell-timezone-series
paru -S --noconfirm haskell-tls
paru -S --noconfirm haskell-transformers-base
paru -S --noconfirm haskell-transformers-compat
paru -S --noconfirm haskell-type-equality
paru -S --noconfirm haskell-typed-process
paru -S --noconfirm haskell-unicode-collation
paru -S --noconfirm haskell-unicode-data
paru -S --noconfirm haskell-unicode-transforms
paru -S --noconfirm haskell-uniplate
paru -S --noconfirm haskell-unix-compat
paru -S --noconfirm haskell-unix-time
paru -S --noconfirm haskell-unliftio
paru -S --noconfirm haskell-unliftio-core
paru -S --noconfirm haskell-unordered-containers
paru -S --noconfirm haskell-utf8-string
paru -S --noconfirm haskell-uuid-types
paru -S --noconfirm haskell-vault
paru -S --noconfirm haskell-vector
paru -S --noconfirm haskell-vector-algorithms
paru -S --noconfirm haskell-void
paru -S --noconfirm haskell-wai
paru -S --noconfirm haskell-wai-conduit
paru -S --noconfirm haskell-x11
paru -S --noconfirm haskell-x11-xft
paru -S --noconfirm haskell-x509
paru -S --noconfirm haskell-x509-store
paru -S --noconfirm haskell-x509-system
paru -S --noconfirm haskell-x509-validation
paru -S --noconfirm haskell-xml
paru -S --noconfirm haskell-xml-conduit
paru -S --noconfirm haskell-xml-types
paru -S --noconfirm haskell-yaml
paru -S --noconfirm haskell-zip-archive
paru -S --noconfirm haskell-zlib
